### ISSUE TITLE
Need More Information of Cast Usage

### ISSUE THREAD

**Issue by th3rdctrl** [ekristen/cast#101]
I am just trying to build my Windows Forensic Machine with WSL2 and try to install SIFT and REMnux on it. I need help about:

1. How does user know which SIFT/REMnux version installed when install it using cast?
2. Is there any way to update the SIFT/REMnux using cast?

Thank in advanced 🙂

**Comment by ekristen** [comment]
Both installs/upgrades are done with the `install` command. It'll output the version being installed when you install. There's currently no way to find out the exact version after the fact that I know of, you could look at the `/var/cache/cast` directory.
