### ISSUE TITLE
FATA[1748] salt-call completed but had failed states

### ISSUE THREAD

**Issue by 5slade** [ekristen/cast#117]
Hi,

Please see error after Saltsalt has been runnning for some time - I've been running in WSL Ubuntu 22.04. I was hoping install would work easily.:

INFO[1748] log file location                             component=installer file=/var/cache/cast/installer/logs/saltstack.log
INFO[1748] results file location                         component=installer file=/var/cache/cast/installer/logs/results.yaml
WARN[1748] first failed state                            comment="One or more requisite failed: sift.python3-packages.defang.sift-python3-packages-defang" component=installer run_num=299 sls=sift.python3-packages.machinae
INFO[1748] statistics                                    component=installer failed=7 success=561 total=568
INFO[1748] salt-call completed but had failed states     component=installer

Please can you assist?
Happy to provide any further info you may need, please let me know

**Comment by ekristen** [comment]
Attach the log file please

**Comment by 5slade** [comment]
Please see attached

[saltstack.log](https://github.com/user-attachments/files/16401321/saltstack.log)

**Comment by ekristen** [comment]
Looks like a bug with perhaps the version of setuptools and/or defang.

**Comment by ekristen** [comment]
Testing locally is working.
