### ISSUE TITLE
Salt keyring not downloaded

### ISSUE THREAD

**Issue by digitalsleuth** [ekristen/cast#134]
Using v0.14.52 and attempting to install REMnux, cast errors out with the following:
```bash
FATA[0001] open /etc/apt/keyrings/salt-archive-keyring-2023.pgp: no such file or directory
```
At this point, the `/etc/apt/keyrings` directory does not exist, and it does not appear to get created if missing. Not sure if this could be related, but I noticed the variables RepoKeyURL and APTRepo in `pkg\saltstack\constants.go`  have quotes surrounding them and not backticks.

**Comment by digitalsleuth** [comment]
Additionally, no log files are generated.

**Comment by ekristen** [comment]
make the directory for me manually retry, let me know the result, I'll patch if that fixes. The constants.go aren't a problem.

**Comment by digitalsleuth** [comment]
Will do. I'll start a new test after my current one finishes. Cheers!

**Comment by digitalsleuth** [comment]
Creating the directory first worked, installation is progressing now.

**Comment by ekristen** [comment]
Ok. I'll patch it.

**Comment by ekristen** [comment]
fixed.
