### ISSUE TITLE
FATA[2910] salt-call completed but had failed states

### ISSUE THREAD

**Issue by Jonnmy** [ekristen/cast#151]
Hi! I have this error when I try to install SIFT. Help!

![Screenshot 2024-12-20 235134](https://github.com/user-attachments/assets/e7848b50-fb82-4f0b-91c6-f1dc29d4f272)

**Comment by digitalsleuth** [comment]
Hi @Jonnmy , this appears to be a SIFT related error, not cast related. Can you please open an Issue over on the [SIFT Issues page](https://github.com/teamdfir/sift/issues)?

Cheers!
