### ISSUE TITLE
Can I upgrade the SIFT Distro using Cast?

### ISSUE THREAD

**Issue by Hack3dlazy** [ekristen/cast#40]
I just installed Sift using Cast without first installing sift CLI. Im trying to install SIFT CLI after the fact and getting invalid OS on Ubuntu 22.04.1. 

I guess my question is do I need to have SIFT CLI installed to update and upgrade SIFT moving forward if i have used cast to install?

If I dont need SIFT CLI to Upgrade how can I update and upgrade SIFT using Cast?

**Comment by ekristen** [comment]
You should be able to just download the cast binary and run the install command. The latest version supports 22.04

**Comment by Hack3dlazy** [comment]
Ok, Cool I installed that way and in the future when an update occurs it seems like I just need to rerun the install for sift and all the new updates and upgrades will apply similar to how SIFT update and SIFT Upgrade worked?

**Comment by ekristen** [comment]
Yes. You've got it. Trying to simplify things.

**Comment by Hack3dlazy** [comment]
Thanks for the quick response @ekristen awesome work on this Cast project
