### ISSUE TITLE
SIFT CLI not installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by MrChieL** [ekristen/cast#42]
sudo install sift produced the below lines / errors:
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: desktop
> downloading v2023.02.06
>> downloading sift-saltstack-v2023.02.06.tar.gz.asc
>> downloading sift-saltstack-v2023.02.06.tar.gz.sha256
>> downloading sift-saltstack-v2023.02.06.tar.gz.sha256.asc
>> downloading sift-saltstack-v2023.02.06.tar.gz
> validating file sift-saltstack-v2023.02.06.tar.gz

Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz

Error: Hashes for sift-saltstack-v2023.02.06.tar.gz do not match. Expected: , Actual: 4076d01731899d27412d25ddeff3b21c4e66308cf802ff8f6e2f5f77414bbbeb  /tmp/sift-saltstack-v2023.02.06.tar.gz

    at validateFile (/snapshot/sift-cli/sift-cli.js:411:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async downloadUpdate (/snapshot/sift-cli/sift-cli.js:478:3)
    at async run (/snapshot/sift-cli/sift-cli.js:772:5)
    at async main (/snapshot/sift-cli/sift-cli.js:795:5)

i am a newbie and learning.  reading the comments, sift cli is deprecated or soon to be by Mar 2023.   And I now am to use cast.  I ran "sudo cast install --mode desktop teamdfir/sift-saltstack"   Resulting to "cast command not found" 
I downloaded cast-main.zip and unzipped it.   what would be the next step(s) or command(s)?  Any feedback is appreciated.

**Comment by ekristen** [comment]
The installation instructions generally cover it. https://github.com/ekristen/cast#installation

You can either download the binary and put it in something like `/usr/local/bin` (or some other directory in your path) or you can install the `.deb` package via `sudo dpkg -i <filename>`
