### ISSUE TITLE
Failure for sift-saltstack installation under wsl2 Ubuntu 20.04

### ISSUE THREAD

**Issue by maxchowhk** [ekristen/cast#44]
INFO[2221] log file location                             component=installer file=/var/cache/cast/installer/logs/saltstack.log
INFO[2221] results file location                         component=installer file=/var/cache/cast/installer/logs/results.yaml
WARN[2221] first failed state                            comment="One or more requisite failed: sift.config.user.sift-config-user, sift.config.timezone.Etc/UTC" component=installer run_num=679 sls=sift.config
INFO[2221] statistics                                    component=installer failed=5 success=670 total=675
INFO[2221] salt-call completed but had failed states     component=installer
FATA[2221] salt-call completed but had failed states

**Comment by ekristen** [comment]
You can do desktop mode under wsl2, you need to specify `mode=server`

**Comment by marienmare** [comment]
@maxchowhk 
You can solving the problem, using to `cast install --mode=server teamdfir/sift-saltstack`

**Comment by ekristen** [comment]
Thanks @marienmare
