### ISSUE TITLE
Success but failed remnux install

### ISSUE THREAD

**Issue by john-crane-69** [ekristen/cast#66]
I'm trying to follow this tutorial to create a malware analysis lab
[Video Here](https://www.youtube.com/watch?v=zyjwo8z3PtU&)

I've ran the following command to install remnu on an ubuntu 20.04:
```powershell
 sudo cast install --mode=addon remnux/salt-states
``` 

Remnux was installed, but I'm getting completed but with failed states
```
INFO[0476] results file location                         component=installer file=/var/cache/cast/installer/logs/results.yaml
WARN[0476] first failed state                            comment="One or more requisite failed: remnux.python3-packages.thug.remnux-python3-packages-thug-packages" component=installer run_num=343 sls=remnux.python3-packages.thug
INFO[0476] statistics                                    component=installer failed=20 success=767 total=787
INFO[0476] salt-call completed but had failed states     component=installer
FATA[0476] salt-call completed but had failed states
``` 

I've run it multiple times and it's the exact same output.

Is there any way to fix this?

**Comment by ekristen** [comment]
There's a log file we can look at in /var/cache/cast and then there's running the log level higher like debug as a cli option. 

Sounds like it doesn't like the python install which is more likely the OS or saltstack.

**Comment by john-crane-69** [comment]
> There's a log file we can look at in /var/cache/cast and then there's running the log level higher like debug as a cli option.
> 
> Sounds like it doesn't like the python install which is more likely the OS or saltstack.
[saltstack.log](https://github.com/ekristen/cast/files/11744117/saltstack.log)
I've Uploaded the slatstack log for you

**Comment by ekristen** [comment]
```Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
  libgstreamer-plugins-bad1.0-0 libwireshark13 libwiretap10 libwsutil11
  python3-colorama
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libemu
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 291 kB of archives.
After this operation, 2704 kB of additional disk space will be used.
Err:1 http://ppa.launchpad.net/remnux/stable/ubuntu focal/main amd64 libemu amd64 1.0.3-2-focal
  499  Request has been forbidden by antivirus [IP: 185.125.190.52 80]
# [ERROR   ] stderr: Running scope as unit: run-r0e8017471f1f4b16876470899b8f3d33.scope
E: Failed to fetch http://ppa.launchpad.net/remnux/stable/ubuntu/pool/main/libe/libemu/libemu_1.0.3-2-focal_amd64.deb  499  Request has been forbidden by antivirus [IP: 185.125.190.52 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
# [ERROR   ] retcode: 100
# [INFO    ] Executing command dpkg-query in directory '/root'
# [ERROR   ] Problem encountered installing package(s). Additional info follows:```

**Comment by john-crane-69** [comment]
> Looks like your network is preventing it from working.
> 
> ```
> Reading state information...
> The following packages were automatically installed and are no longer required:
>   chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
>   libgstreamer-plugins-bad1.0-0 libwireshark13 libwiretap10 libwsutil11
>   python3-colorama
> Use 'sudo apt autoremove' to remove them.
> The following NEW packages will be installed:
>   libemu
> 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
> Need to get 291 kB of archives.
> After this operation, 2704 kB of additional disk space will be used.
> Err:1 http://ppa.launchpad.net/remnux/stable/ubuntu focal/main amd64 libemu amd64 1.0.3-2-focal
>   499  Request has been forbidden by antivirus [IP: 185.125.190.52 80]
> # [ERROR   ] stderr: Running scope as unit: run-r0e8017471f1f4b16876470899b8f3d33.scope
> E: Failed to fetch http://ppa.launchpad.net/remnux/stable/ubuntu/pool/main/libe/libemu/libemu_1.0.3-2-focal_amd64.deb  499  Request has been forbidden by antivirus [IP: 185.125.190.52 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
> # [ERROR   ] retcode: 100
> # [INFO    ] Executing command dpkg-query in directory '/root'
> # [ERROR   ] Problem encountered installing package(s). Additional info follows:```
> ```

OMG it was Kaspersky, I've noticed that with VMs it doesn't let me upgrade, I guess the settings are too aggressive or something which is good in my case since I'm working with malware, I tried it again with Kaspersky disabled, and it reduced the failed down to 6.
I've rebooted and tried again multiple times and it remains at 6.
Here's the new log: [saltstack.log](https://github.com/ekristen/cast/files/11748619/saltstack.log)

**Comment by ekristen** [comment]
```# [INFO    ] Completed state [deb [arch=amd64 signed-by=/usr/share/keyrings/DOCKER-PGP-KEY.asc] https://download.docker.com/linux/ubuntu focal stable] at time 16:30:36.050779 (duration_in_ms=2.048)
# [INFO    ] Running state [/usr/share/keyrings/DRAIOS-GPG-KEY.asc] at time 16:30:36.050938
# [INFO    ] Executing state file.managed for [/usr/share/keyrings/DRAIOS-GPG-KEY.asc]
# [ERROR   ] Failed to cache https://download.sysdig.com/DRAIOS-GPG-KEY.public: Error: [Errno 111] Connection refused reading /DRAIOS-GPG-KEY.public
# [INFO    ] Completed state [/usr/share/keyrings/DRAIOS-GPG-KEY.asc] at time 16:30:36.077901 (duration_in_ms=26.963)
# [INFO    ] Running state [/usr/share/keyrings/INETSIM-GPG-KEY.asc] at time 16:30:36.079351
# [INFO    ] Executing state file.managed for [/usr/share/keyrings/INETSIM-GPG-KEY.asc]
# [INFO    ] File /usr/share/keyrings/INETSIM-GPG-KEY.asc is in the correct stat```

For some reason it can't get the pgp key.

**Comment by john-crane-69** [comment]
> ```
> # [INFO    ] Running state [/usr/share/keyrings/DRAIOS-GPG-KEY.asc] at time 16:30:36.050938
> # [INFO    ] Executing state file.managed for [/usr/share/keyrings/DRAIOS-GPG-KEY.asc]
> # [ERROR   ] Failed to cache https://download.sysdig.com/DRAIOS-GPG-KEY.public: Error: [Errno 111] Connection refused reading /DRAIOS-GPG-KEY.public
> # [INFO    ] Completed state [/usr/share/keyrings/DRAIOS-GPG-KEY.asc] at time 16:30:36.077901 (duration_in_ms=26.963)
> # [INFO    ] Running state [/usr/share/keyrings/INETSIM-GPG-KEY.asc] at time 16:30:36.079351
> # [INFO    ] Executing state file.managed for [/usr/share/keyrings/INETSIM-GPG-KEY.asc]
> # [INFO    ] File /usr/share/keyrings/INETSIM-GPG-KEY.asc is in the correct stat```
> 
> For some reason it can't get the pgp key.
> ```

I've turned off Windscribe VPN and performed the installation one more time and everything installed successfully.

Thank you so much for the help, now I'll keep in mind in the future if an installation fails check the VPN and the antivirus first.
