### ISSUE TITLE
 Error when trying to Install SIFT CLI #610 

### ISSUE THREAD

**Issue by lbudino** [ekristen/cast#70]
sudo sift install

    sift-cli@1.14.0-rc1+0-g0582d2b
    sift-version: notinstalled

    mode: desktop
    downloading v2023.02.06

        downloading sift-saltstack-v2023.02.06.tar.gz.asc
        downloading sift-saltstack-v2023.02.06.tar.gz.sha256
        downloading sift-saltstack-v2023.02.06.tar.gz.sha256.asc
        /snapshot/sift-cli/sift-cli.js:357
        throw new Error(res.body)
        ^

Error
at Request. (/snapshot/sift-cli/sift-cli.js:357:17)
at Request.emit (events.js:400:28)
at Request.onRequestResponse (/snapshot/sift-cli/node_modules/request/request.js:1059:10)
at ClientRequest.emit (events.js:400:28)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
at TLSSocket.socketOnData (_http_client.js:515:22)
at TLSSocket.emit (events.js:400:28)
at addChunk (internal/streams/readable.js:293:12)
at readableAddChunk (internal/streams/readable.js:267:9)
at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

Thank you in advance for your help

**Comment by digitalsleuth** [comment]
Hi @lbudino , when @ekristen recommended for you to use Cast in place of the deprecated sift-cli, the intent was for you to download and install cast [from here](https://github.com/ekristen/cast/releases/latest) and use this to install SIFT.

You can find the commands to install SIFT using cast on the main page of the [SIFT repo](https://github.com/teamdfir/sift).

Cheers!

**Comment by Devops-sudarshan** [comment]
Hi @digitalsleuth, I am trying to install SIFT on VM (Ubuntu 22.04) with help of CAST. After 50 mins of installation it is showing Low disk space Filesystem root. I was trying this in Ubuntu-20.04 but facing same issue. 

I have 52 GB free space but not able to resize it.


![image](https://github.com/ekristen/cast/assets/91316825/23580280-470a-48f2-9f7a-ad90bb292213)

![image](https://github.com/ekristen/cast/assets/91316825/773eb48b-afe5-403f-978c-8574f6cd9160)

![image](https://github.com/ekristen/cast/assets/91316825/a026373d-f52c-4441-9ab7-738a71a3f500)

**Comment by digitalsleuth** [comment]
Hi @Devops-sudarshan , this isn't a Cast issue, and since you've already opened an Issue for this in the `teamdfir/sift` Github, I'll respond there.

**Comment by ekristen** [comment]
Your root partition is only 13GB, you do indeed have 52GB of freespace but you have to expand your partition to include that space.

**Comment by ekristen** [comment]
This isn't an issue with cast or sift, so I'm going to close this out.
